# Generated by Django 4.2.2 on 2023-07-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_instructor_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
