# Generated by Django 4.2.2 on 2023-07-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gitHub',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserSocial',
        ),
    ]
