# Generated by Django 4.2.2 on 2023-07-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_course_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
    ]
