# Generated by Django 4.2.2 on 2023-07-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_course_updated_at_alter_course_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='who_is_the_course_for',
            new_name='targeted_audience',
        ),
    ]
